config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:new, :create, :edit, :update, :destroy] do 
    resources :comments, only: :create
  end

  resources :likes, only: :create do
    collection do
      delete :destroy
    end
  end 
  
  resources :musics, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  
  resources :powerpoints

  post 'create_powerpoint/:id', to: "powerpoints#create_powerpoint", as: "export_powerpoint"
  get 'download/:id', to: "powerpoints#download", as: "download"

  devise_for :users
  root "site#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :pictures, as: :pictureable, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new; end

  def create
    @post = Post.find(params[:post_id])
    comment = Comment.new(comment_params)
    comment.user = current_user
    comment.post = @post
    if comment.valid?
      comment.save
      if params[:comment][:attachment].present?
        file = upload_picture(params[:comment][:attachment])
        comment.pictures.create(picture_uri: file[:path], picture_type: file[:type], picture_name: file[:name]) 
      end
    else
      render_flash(:alert, full_messages(comment.errors.full_messages))
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/views/comments/_form.html.erb
<%= form_with model: Comment.new, url: post_comments_path(post), class: "comment-form" do |f| %>
  <%= f.text_field :body, class: "form-control", placeholder: "Enter comment ..."%>
  <%= f.file_field :attachment, id: "comment-document", class:"attachment attachment-photo d-none"%>
  <label for="comment-document" data-id="<%= post.id %>" class="upload-icon comment-document pointer">
    <%= image_tag "icons/paperclip-blue"%>
  </label>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>
<p class="filename-document-<%=post.id%> mb-2"></p>

app/views/comments/_list.html.erb
<% post.comments.each do |comment| %>
  <div class="comment">
    <span class="comment-author"><%= comment.user.username %></span>
    <%= comment.body %>
    <div>
      <% comment.pictures.each do |image|%>
        <%= image_tag(image.picture_uri, :size => "100x60", class: "comment-image") if image.picture_uri && is_image(image.picture_type) %>
        <%= link_to(image.picture_name, image.picture_uri, target: :blank, class: "open-document") if image.picture_uri && !is_image(image.picture_type) %>
      <% end %>
    </div>
  </div>
  <div class="comment-like">
    <%= turbo_frame_tag "like-#{comment.id}" do %>
      <% if find_object_like(comment) %>
        <%= link_to "Liked", likes_path(likeable_type: "Comment", likeable_id: comment.id), data: {turbo_method: :delete}, class: 'liked'%>
      <% else %>
        <%= link_to "Like", likes_path(likeable_type: "Comment", likeable_id: comment.id), data: {turbo_method: :post}, class: 'like'%>
      <% end %>
    <% end %>
    <div class="edit">Edit</div>
  </div>
<% end%>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.update "comment-form-#{@post.id}" do %>
  <%= render partial: "comments/form", locals: {post: @post} %>
<% end %>

<%= turbo_stream.update "post-comments-list-#{@post.id}" do %>
  <%= render partial: "comments/list", locals: {post: @post} %>
<% end %>

<%= turbo_stream.update "post-comments-count-#{@post.id}" do %>
  <%= pluralize(@post.comments.count, "comment") %>
<% end %>

app/views/comments/new.turbo_stream.erb
<%= turbo_stream.update "comment-form" do %>
  <%= render partial: "comments/form", locals: {post: Post.new} %>
<% end %>