config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:new, :create, :edit, :update, :destroy] do 
    resources :comments, only: :create
  end

  resources :likes, only: :create do
    collection do
      delete :destroy
    end
  end 
  
  resources :musics, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  
  resources :powerpoints

  post 'create_powerpoint/:id', to: "powerpoints#create_powerpoint", as: "export_powerpoint"
  get 'download/:id', to: "powerpoints#download", as: "download"

  devise_for :users
  root "site#index"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  # belongs_to :post
  belongs_to :likeable, polymorphic: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_likeable, only: [:create, :destroy]
  before_action :user_login_required, only: [:create]

  def create 
    @likeable_save = Like.new(likeable: @likeable, user: current_user)
    if @likeable_save.valid?
      @likeable_save.save
    else
      render_flash(:alert, full_messages(@likeable_save.errors.full_messages))
    end
  end

  def destroy
    Like.where(likeable: @likeable, user: current_user).delete_all
  end

  private 

    def set_likeable
      @likeable = params[:likeable_type].constantize.find(params[:likeable_id])
    end
end

app/views/likes/create.html.erb
<%#= turbo_frame_tag "post-likes" do %>
  <%#= button_to "", post_likes_path(@post), class:"post-actions-unlike", method: :delete%>
<%# end %>

app/views/likes/create.turbo_stream.erb
<%= turbo_stream.update "post-likes-count-#{@likeable.id}" do %>
  <%= pluralize(@likeable.likes.count, "like") %>
<% end %>

<%= turbo_stream.update "post-likes-#{@likeable.id}" do %>
  <%= button_to "", likes_path, class: "post-actions-unlike", method: :delete, params: {likeable_type: "Post", likeable_id: @likeable.id} %>
<% end %>

<%= turbo_stream.update "like-#{@likeable.id}" do %>
  <%= link_to "Liked", likes_path(likeable_type: "Comment", likeable_id: @likeable.id), data: {turbo_method: :delete}, class: 'liked'%>
<% end %>

app/views/likes/destroy.html.erb
<%#= turbo_frame_tag "post-likes" do %>
  <%#= button_to "", post_likes_path(@post), class: "post-actions-like" %>
<%# end %>

app/views/likes/destroy.turbo_stream.erb
<%= turbo_stream.update "post-likes-count-#{@likeable.id}" do %>
  <%= pluralize(@likeable.likes.count, "like") %>
<% end %>

<%= turbo_stream.update "post-likes-#{@likeable.id}" do %>
  <%= button_to "", likes_path, params: {likeable_type: "Post", likeable_id: @likeable.id}, class:"post-actions-like"%>
<% end %>

<%= turbo_stream.update "like-#{@likeable.id}" do %>
  <%= link_to "Like", likes_path(likeable_type: "Comment", likeable_id: @likeable.id), data: {turbo_method: :post}, class: 'like'%>
<% end %>