config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:new, :create, :edit, :update, :destroy] do 
    resources :comments, only: :create
  end

  resources :likes, only: :create do
    collection do
      delete :destroy
    end
  end 
  
  resources :musics, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  
  resources :powerpoints

  post 'create_powerpoint/:id', to: "powerpoints#create_powerpoint", as: "export_powerpoint"
  get 'download/:id', to: "powerpoints#download", as: "download"

  devise_for :users
  root "site#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :pictures, as: :pictureable, dependent: :destroy

  validates :title, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :user_login_required, only: [:create, :new]
  before_action :set_post, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.valid?
      @post.save
      if params[:post][:attachment].present?
        file = upload_picture(params[:post][:attachment])
        @post.pictures.create(picture_uri: file[:path], picture_type: file[:type], picture_name: file[:name]) 
      end
    else
      render_flash(:alert, full_messages(@post.errors.full_messages))
    end
  end

  def edit
  end

  def update 
    if @post.update(post_params)
      if params[:post][:attachment].present?
        file = upload_picture(params[:post][:attachment])
        pictureable = @post.pictures.first
        pictureable.update(picture_uri: file[:path], picture_type: file[:type], picture_name: file[:name])
      end
    else
      render_flash(:alert, full_messages(@post.errors.full_messages))
    end
  end

  def destroy
    @post.destroy
  end

  private

    def set_post 
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def format_created_at created_at
    time_ago_in_words(created_at)
  end

  def find_object_like object
    object.likes.find_by(likeable: object, user: current_user)
  end

end

app/views/posts/_form.html.erb
<%= turbo_frame_tag "post-form" do %>
  <%#= form_with model: Post.new do |f| %>
    <%#= f.text_field :body %>
    <%#= f.submit "Send" %>
  <%# end %>
  <div class="row">
    <div class="col-md-12 mt-4 new-post">
      <div class="row post-container col-md-12">
        <div class="avatar-container">
          <%= image_tag "avatars/01", class: "avatar" %>
        </div>
        <div class="form">
          <%= form_with model: @post do |f| %>
          <div>
            <%= f.text_field :title, class: 'form-control', placeholder: 'Title ...' %>
          </div>
          <div class="mt-2">
            <%= f.text_area :body, rows: '4', class: 'form-control', placeholder: 'Description ...'%>
          </div>
          <div>
            <div class="mt-2 d-flex justify-content-between align-items-center">
              <div class="d-flex align-items-center">
                <%= f.file_field :attachment, id: "upload-photo", class:"attachment attachment-photo d-none"%>
                <label for="upload-photo" class="upload-icon d-flex attachment-btn pointer align-items-center">
                  <%= image_tag "icons/image-gallery-blue"%>
                  <p>Photo</p>
                </label>
              </div>
              <div class="d-flex align-items-center">
                <%= f.file_field :attachment, id: "upload-document", class:"attachment attachment-photo d-none"%>
                <label for="upload-document" class="upload-icon attachment-btn d-flex pointer align-items-center">
                  <%= image_tag "icons/paperclip-blue"%>
                  <p>Document</p>
                </label>
              </div>
              <%= f.submit "Post", class: 'btn btn-primary', "data-bs-dismiss": "#{@post.id.present? ? 'modal': ''}" %>
            </div>
            <p class="filename"></p>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" data-controller="modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Edit <%=post.title%></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <%= render "posts/form", post: post %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="row" id="post-<%=post.id%>">
  <div class="col-md-12">
    <div class="post col-md-8 offset-md-2">
      <div class="header-post">
        <div class="post-author">
          <div class="avatar avatar-<%=rand(1..27)%>"></div>
          <div><%= post.user.username %></div>
        </div>
        <div class="action-post">
          <% if current_user == post.user %>
            <div class="dot-post" data-controller="post">
              <p data-action="click->post#showEdit" data-post-id-param ="<%=post.id%>"
                data-post-show-param="false" data-post-target="show" data-post-url-param="<%=post_path(post)%>"
                class="text-end pointer">&#9675; &#9675; &#9675;</p>
              <span class="edit-post" data-post-target="output">
              </span>
            </div>
          <% end %>
          <%= format_created_at(post.created_at) %>
        </div>
      </div>
      <div class="post-body">
        <h3><%= post.title %></h3>
        <p><%= post.body %></p>
        <div class="text-center mt-3">
          <% post.pictures.each do |image|%>
            <%= image_tag(image.picture_uri, :size => "360x200") if image.picture_uri && is_image(image.picture_type) %>
            <%= link_to(image.picture_name, image.picture_uri, target: :blank, class: "open-document") if image.picture_uri && !is_image(image.picture_type) %>
          <% end %>
        </div>
      </div>
      <div class="post-actions">
        <div class="like-container">
          <%= turbo_frame_tag "post-likes-#{post.id}" do %>
            <% if find_object_like(post).nil? %>
              <%= button_to "", likes_path, params: {likeable_type: "Post", likeable_id: post.id}, class:"post-actions-like"%>
            <% else %>
              <%= button_to "", likes_path, class: "post-actions-unlike", method: :delete, params: {likeable_type: "Post", likeable_id: post.id} %>
            <% end %>
          <% end %>
          <div id="post-likes-count-<%=post.id%>"><%= pluralize(post.likes.count, "like") %></div>
        </div>
        <div class="post-action-comments"><div id="post-comments-count-<%=post.id%>"><%= pluralize(post.comments.count, "comment") %></div></div>
      </div>
      <div class="post-comments">
        <div id="comment-form-<%=post.id%>">
          <%= render partial: "comments/form", locals: {post: post}%>
        </div>
        <div class="comments-list" id="post-comments-list-<%=post.id%>">
          <%= render partial: "comments/list", locals: {post: post}%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts" do %>
  <%= render partial: "post", locals: {post: @post}%>
<% end %>

<%= turbo_stream.update "post-form" do %>
  <%= render "posts/form"%>
<% end %>

<%= turbo_stream.update "flash", partial: "shared/flash", locals: { msg_type: :notice, message: "Created a new post!" } %>

app/views/posts/destroy.turbo_stream.erb
<%= turbo_stream.remove "post-#{@post.id}" do %>
    <%= render partial: "post", locals: {post: @post}%>
<% end %>

<%= turbo_stream.update "flash", partial: "shared/flash", locals: { msg_type: :notice, message: "This post is removed!" } %>

app/views/posts/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "posts/form_modal", locals: { post: @post } %>
<% end %>

<%= turbo_stream.update "flash", partial: "shared/flash", locals: { msg_type: :notice, message: "This post is updated!" } %>

app/views/posts/new.html.erb
<%= turbo_frame_tag "post-form" do %>
  <%#= form_with model: @post do |f| %>
    <%#= f.text_field :body %>
    <%#= f.submit "Send" %>
  <%# end %>
  <div id="post-form">
    <%= render partial: "posts/form", locals: {post: @post} %>
  </div> 
<% end %>

app/views/posts/update.turbo_stream.erb
<%= turbo_stream.replace "post-#{@post.id}" do %>
    <%= render partial: "post", locals: {post: @post}%>
<% end %>