config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:new, :create, :edit, :update, :destroy] do 
    resources :comments, only: :create
  end

  resources :likes, only: :create do
    collection do
      delete :destroy
    end
  end 
  
  resources :musics, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  
  resources :powerpoints

  post 'create_powerpoint/:id', to: "powerpoints#create_powerpoint", as: "export_powerpoint"
  get 'download/:id', to: "powerpoints#download", as: "download"

  devise_for :users
  root "site#index"
end

app/models/music.rb
class Music < ApplicationRecord
  # has_rich_text :lyric
  belongs_to :user
  validates :name, presence: true
  validates :auth, presence: true

  has_many :lyrics
  has_many :music_user, through: :lyrics, source: :user

end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:edit, :show, :update, :destroy]

  def index
    @musics = Music.all.order(created_at: :desc)
  end

  def new
    @music = Music.new
  end

  def create
    @music = Music.new(music_params)
    @music.user_id = current_user.id
    if @music.valid?
      @music.save
    else
      render_flash(:alert, full_messages(@music.errors.full_messages))
    end
  end

  def edit
  end

  def show
  end

  def update
    if @music.user_id == current_user.id
      if @music.update(music_params)

      else
        render_flash(:alert, full_messages(@music.errors.full_messages))
      end
    end
    lyric = @music.lyrics.find_or_initialize_by(user_id: current_user.id)
    if lyric.update(lyric_params.merge(user_id: current_user.id, powerpoint_file: "#{replace_name}.pptx"))
    else
      render_flash(:alert, full_messages(@music.errors.full_messages))
    end
  end

  def destroy
  end

  private

    def set_music 
      @music = Music.find(params[:id])
    end

    def music_params
      params.require(:music).permit(:name, :lyric, :auth)
    end

    def lyric_params
      params.require(:music).permit(:lyric)
    end

    def replace_name
      @music.name.downcase.gsub(' ', '_')
    end
end

app/helpers/music_helper.rb
module MusicHelper
  def find_edit_lyric lyrics, current_user
    lyrics.find_by(user_id: current_user.id)
  end
end

app/views/musics/_form.html.erb
<%= turbo_frame_tag "music-form" do %>
  <%= link_to musics_path, class: "text-dark text-decoration-none mt-2" do %>
    <%= image_tag "icons/back"%> 
    Back
  <% end %>
  <div class="row">
    <div class="row music-container col-md-12">
      <div class="form">
        <%= form_with model: music do |f| %>
        <div class="row">
          <div class="col-4">
            <div class="mt-2">
              <%= f.text_field :name, class: 'form-control', placeholder: 'Name ...' %>
            </div>
            <div class="mt-2">
              <%= f.text_field :auth, rows: '4', class: 'form-control', placeholder: 'Author ...'%>
            </div>          
          </div>
          <% if find_edit_lyric(@music.lyrics, current_user).present? %>
            <div class="col-8 mt-2">
              <%= f.rich_text_area :lyric, rows: '4', class: 'form-control', placeholder: 'Lyric ...', value: find_edit_lyric(@music.lyrics, current_user).lyric %>
            </div>
          <% else %>
            <div class="col-8 mt-2">
                <%= f.rich_text_area :lyric, rows: '4', class: 'form-control', placeholder: 'Lyric ...'%>
            </div>
          <% end %>
        </div>
        <div class="mt-2 text-center">
          <%= f.submit "Post", class: 'btn btn-primary form-control' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/musics/_music.html.erb
<div class="music-item pointer card mt-3 mb-3" data-controller="music" data-action="click->music#detail" data-music-url-param="<%=music_path(music)%>" id="music_<%= music.id %>">
  <div class="card-body">
    <h5 class="card-title"><%= music.name %></h5>
    <p class="card-text auth">Author: <%= music.auth %></p>
  </div>
  <div class="card-footer text-muted created_at">
    By: <%= music.user.username %>
    <%= format_datetime(music.created_at) %>
  </div>
</div>

app/views/musics/destroy.html.erb
<h1>Music#destroy</h1>
<p>Find me in app/views/music/destroy.html.erb</p>

app/views/musics/edit.html.erb
<%= render "form", music: @music %>

app/views/musics/index.html.erb
<div class="row list-container">
  <div class="col-md-4 h-100 border">
    <p>Name</p>
    <small class="text-danger">The songs that are not in the list you can add it </small>
    <hr>
    <% @musics.each do |music|%>
      <%= render music %>
    <% end %>
  </div>
  <div class="col-md-8 h-100 border lyric-container">
    <div class="d-flex justify-content-between align-items-center">
      <div>
        <p>Lyric</p>
        <small class="text-danger">Each slide is spaced about 1 line apart</small>
      </div>
      <%= link_to "+ New", new_music_path, class: "btn btn-primary" %>
    </div>
    <hr>
    <div id="lyric"></div>
    <div id="btn-actions">
    </div>
  </div>
</div>
<!-- <script type="text/javascript" src="/javascripts/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/javascripts/jszip.min.js"></script>
<script type="text/javascript" src="/javascripts/filereader.js"></script>
<script type="text/javascript" src="/javascripts/d3.min.js"></script>
<script type="text/javascript" src="/javascripts/nv.d3.min.js"></script>
<script type="text/javascript" src="/javascripts/pptxjs.js"></script>
<script type="text/javascript" src="/javascripts/divs2slides.js"></script>
<link rel="stylesheet" href="/css/pptxjs.css">
<link rel="stylesheet" href="/css/nv.d3.min.css">
<%= javascript_tag nonce: true do -%>
  $("#slide-resolte-contaniner").pptxToHtml({ 
    pptxFileUrl: "/powerpoints/faded.pptx", 
    slidesScale: "30%", 
    slideMode: false, 
    keyBoardShortCut: false 
  }); 
<% end -%> -->

app/views/musics/new.html.erb
<%= render "form", music: @music %>

app/views/musics/show.html.erb
<%= render "form", music: @music %>

app/views/musics/show.turbo_stream.erb
<%= turbo_stream.update "lyric" do %>
  <% if find_edit_lyric(@music.lyrics, current_user).present? %>
    <%= find_edit_lyric(@music.lyrics, current_user).lyric.html_safe %>
  <% else %>
    <%= @music.lyric.html_safe %>
  <% end %>
<% end %>

<%= turbo_stream.update "btn-actions" do %>
  <%= link_to "Edit", edit_music_path(@music), class: "music-action"%>
  <%= link_to "Preview", export_powerpoint_path(@music), data: {turbo_method: :post}, class: "music-action"%>
  <%= link_to "Export", download_path(@music), data: { turbo_method: :get }, target: "_blank", class: "music-action"%>
<% end %>

app/views/musics/update.html.erb
<h1>Music#update</h1>
<p>Find me in app/views/music/update.html.erb</p>

app/views/musics/update.turbo_stream.erb
<%= turbo_stream.update "flash", partial: "shared/flash", locals: { msg_type: :notice, message: "This music is updated!" } %>